### ISSUE TITLE
npm packages fails to run

### ISSUE THREAD

**Issue by sigmaSd** [google/magika#55]
```ts
import { readFile } from "fs/promises";
import { Magika } from "magika";

const data = await readFile("./package.json");
const magika = new Magika();
await magika.load();
const prediction = await magika.identifyBytes(data);
console.log(prediction);
```
```
/node_modules/magika/magika.js:73
  async load({ modelURL, configURL }) {
               ^

TypeError: Cannot destructure property 'modelURL' of 'undefined' as it is undefined.
    at Magika.load (file:///home/mrcool/dev/m/node_modules/magika/magika.js:73:16)
    at file:///home/mrcool/dev/m/index.js:6:14
```

"magika": "^0.2.5"
Node.js v20.10.0

**Comment by TheMythologist** [comment]
Will be fixed by https://github.com/google/magika/pull/52

**Comment by reyammer** [comment]
Seems fixed by the PR. Thanks @TheMythologist! [Please reopen if this is still broken]
